# Generated by Django 5.2.15 on 2026-06-27 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100) or fixed amount in Rs.', max_digits=8)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percentage coupons', max_digits=8, null=True)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value to apply this coupon', max_digits=10)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max total uses. Leave blank for unlimited.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Max uses per customer')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
